db:
  image: postgres
  restart: always
  expose:
      - "5432"
  ports:
   - 5432:5432
  volumes:
  - postgresdata:/var/lib/postgresql/data
  environment:
    POSTGRES_PASSWORD: 123

servermineteste:
  image: minetest-server
  restart: always
  links:
    - db:postgres
  ports:
    - 30080:30080/udp
